= Technology Stack used by Planner
:icons:
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

== Overview
The Planner is an Angular app built on top of Node.js. It can run as a standalone app, or be used as a library to be integrated into the link:./fabric8-platform[Fabric8 Platform].

Development or deployment of Planner is fairly platform agnostic, so we can skip the operating system requirements and discuss from the runtime environment to way-up.

== Development Runtime
Planner uses *`Node.js`* as the platform-runtime, on top of which it builds; on that line, we use *`npm`* for resolving and distributing packages for the project.

We keep ourselves compatible with the latest stable releases of *`Node.js`* & *`npm`* - however, *`Node.js >= 6.xx`* & *`npm >= 3.xx`* releases should work and are recommended.

== Development Pipeline

[NOTE]
_stub section, needs expansion_

Task Runner::
Gulp

Build System::
Gulp, webpack

Test Framework::
Karma, Protractor, PhantomJS

CI/CD::
Jenkins

Release Framework::
semantic-release

Deployment::
Docker, nginx

== Application Framework
We use *`Angular 4`* to develop Planner. Main application code resides in `./src`, in which the `./src/app` contains all the application logics, subdivided into specific functional groups. 

== Programming Languages
For development ease, we dont use HTML, CSS, JS as is, but Angular Templates, Less and TypeScript instead.

This requires us to pre-process and build the source-codes into consumable package, but that is automated and this overall accelerates the development process and eases code maintenance.
